CREATE TABLE "account" (
  "account_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "email" varchar(255) NOT NULL,
  "hashed_password" varchar(255) NOT NULL,
  "role" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

-- CREATE TABLE "film" (
--   "film_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   "name" varchar(255) NOT NULL,
--   "type" varchar(255) NOT NULL,
--   "yt_link" varchar(255) NOT NULL,
--   "active" numeric NOT NULL,
--   "created_at" timestamp DEFAULT (now())
-- );

-- CREATE TABLE "product" (
--   "product_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   "name" varchar(255) NOT NULL,
--   "description" varchar(4096),
--   "images_url" varchar(255),
--   "price" numeric NOT NULL,
--   "active" numeric NOT NULL,
--   "type_id" bigint NOT NULL DEFAULT (0),
--   "created_at" timestamp DEFAULT (now())
-- );

-- CREATE TABLE "product_type" (
--   "type_id" SERIAL PRIMARY KEY,
--   "type_name" varchar(255)
-- );

-- CREATE TABLE "product_order" (
--   "order_id" bigint NOT NULL,
--   "product_id" bigint NOT NULL,
--   "created_at" timestamp DEFAULT (now()),
--   PRIMARY KEY ("order_id", "product_id")
-- );

-- CREATE TABLE "order" (
--   "order_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   "customer_name" varchar NOT NULL,
--   "status_id" bigint NOT NULL,
--   "order_ammaount" varchar NOT NULL,
--   "created_at" timestamp DEFAULT (now())
-- );

-- CREATE TABLE "order_status" (
--   "status_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "status_name" varchar NOT NULL
-- );

CREATE UNIQUE INDEX ON "account" ("email");

-- ALTER TABLE "product" ADD FOREIGN KEY ("type_id") REFERENCES "product_type" ("type_id");

-- ALTER TABLE "product_order" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("order_id");

-- ALTER TABLE "product_order" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id");

-- ALTER TABLE "order" ADD FOREIGN KEY ("status_id") REFERENCES "order_status" ("status_id");
