CREATE TABLE public.account (
	account_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NOT NULL,
	hashed_password varchar(255) NOT NULL,
	"role" varchar(255) NOT NULL,
	created_at timestamp DEFAULT now() NULL,
	CONSTRAINT account_pk PRIMARY KEY (account_id)
);
CREATE UNIQUE INDEX account_email_idx1 ON public.account USING btree (email);


CREATE TABLE public.product (
	product_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	name varchar(255) NOT NULL,
	description varchar(4096) NULL,
	images_url varchar(255) NULL,
	price numeric NOT NULL,
	active numeric NOT NULL,
	created_at timestamp DEFAULT now() NULL,
	type_id int4 DEFAULT 0 NOT NULL,
	CONSTRAINT product_pk PRIMARY KEY (product_id),
	CONSTRAINT fk_product_type FOREIGN KEY (type_id) REFERENCES public.product_type(type_id)
);

CREATE TABLE public.film (
	film_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	"type" varchar(255) NULL,
	yt_link varchar(255) NULL,
	active numeric NOT NULL,
	created_at timestamp DEFAULT now() NULL,
	CONSTRAINT film_pk PRIMARY KEY (film_id)
);

-- CREATE TABLE "film" (
--   "film_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   "name" varchar(255) NOT NULL,
--   "type" varchar(255) NOT NULL,
--   "yt_link" varchar(255) NOT NULL,
--   "active" numeric NOT NULL,
--   "created_at" timestamp DEFAULT (now())
-- );

-- CREATE TABLE "product" (
--   "product_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   "name" varchar(255) NOT NULL,
--   "description" varchar(4096),
--   "images_url" varchar(255),
--   "price" numeric NOT NULL,
--   "active" numeric NOT NULL,
--   "type_id" bigint NOT NULL DEFAULT (0),
--   "created_at" timestamp DEFAULT (now())
-- );

-- CREATE TABLE "product_type" (
--   "type_id" SERIAL PRIMARY KEY,
--   "type_name" varchar(255)
-- );

-- CREATE TABLE "product_order" (
--   "order_id" bigint NOT NULL,
--   "product_id" bigint NOT NULL,
--   "created_at" timestamp DEFAULT (now()),
--   PRIMARY KEY ("order_id", "product_id")
-- );

-- CREATE TABLE "order" (
--   "order_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
--   "customer_name" varchar NOT NULL,
--   "status_id" bigint NOT NULL,
--   "order_ammaount" varchar NOT NULL,
--   "created_at" timestamp DEFAULT (now())
-- );

-- CREATE TABLE "order_status" (
--   "status_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "status_name" varchar NOT NULL
-- );

CREATE UNIQUE INDEX ON "account" ("email");

-- ALTER TABLE "product" ADD FOREIGN KEY ("type_id") REFERENCES "product_type" ("type_id");

-- ALTER TABLE "product_order" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("order_id");

-- ALTER TABLE "product_order" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id");

-- ALTER TABLE "order" ADD FOREIGN KEY ("status_id") REFERENCES "order_status" ("status_id");
