// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderID       int64
	CustomerName  string
	StatusID      int64
	OrderAmmaount string
	CreatedAt     pgtype.Timestamp
}

type OrderStatus struct {
	StatusID   int64
	StatusName string
}

type Product struct {
	ProductID   int64
	Name        string
	Description pgtype.Text
	ImagesUrl   pgtype.Text
	Price       pgtype.Numeric
	Active      pgtype.Numeric
	TypeID      int64
	CreatedAt   pgtype.Timestamp
}

type ProductOrder struct {
	OrderID   int64
	ProductID int64
	CreatedAt pgtype.Timestamp
}

type ProductType struct {
	TypeID   int32
	TypeName pgtype.Text
}
