// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Account struct {
	AccountID      int64        `json:"account_id"`
	Email          string       `json:"email"`
	HashedPassword string       `json:"hashed_password"`
	Role           string       `json:"role"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type Product struct {
	ProductID   int64          `json:"product_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ImagesUrl   sql.NullString `json:"images_url"`
	Price       string         `json:"price"`
	Active      string         `json:"active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	TypeID      int32          `json:"type_id"`
}
