// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ProductID   int64
	Name        string
	Description pgtype.Text
	ImagesUrl   pgtype.Text
	Price       pgtype.Numeric
	Active      pgtype.Numeric
	CreatedAt   pgtype.Timestamp
	TypeID      int32
}

type ProductType struct {
	TypeID   int64
	TypeName string
}
