CREATE TABLE public.product (
	product_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	description varchar(4096) NULL,
	images_url varchar(255) NULL,
	price numeric NOT NULL,
	active numeric NOT NULL,
	created_at timestamp DEFAULT now() NULL,
	type_id int4 DEFAULT 0 NOT NULL,
	CONSTRAINT product_pk PRIMARY KEY (product_id),
	CONSTRAINT fk_product_type FOREIGN KEY (type_id) REFERENCES public.product_type(type_id)
);

CREATE TABLE public.product_type (
	type_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	type_name varchar(255) NOT NULL,
	CONSTRAINT product_type_pk PRIMARY KEY (type_id)
);