// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.26.1
// source: rpc_film.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFilmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	YtLink string `protobuf:"bytes,3,opt,name=yt_link,json=ytLink,proto3" json:"yt_link,omitempty"`
	Active int64  `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *CreateFilmRequest) Reset() {
	*x = CreateFilmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_film_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFilmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilmRequest) ProtoMessage() {}

func (x *CreateFilmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_film_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilmRequest.ProtoReflect.Descriptor instead.
func (*CreateFilmRequest) Descriptor() ([]byte, []int) {
	return file_rpc_film_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFilmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFilmRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateFilmRequest) GetYtLink() string {
	if x != nil {
		return x.YtLink
	}
	return ""
}

func (x *CreateFilmRequest) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

type GetFilmListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFilmListRequest) Reset() {
	*x = GetFilmListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_film_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilmListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilmListRequest) ProtoMessage() {}

func (x *GetFilmListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_film_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilmListRequest.ProtoReflect.Descriptor instead.
func (*GetFilmListRequest) Descriptor() ([]byte, []int) {
	return file_rpc_film_proto_rawDescGZIP(), []int{1}
}

type GetFilmListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Films []*Film `protobuf:"bytes,1,rep,name=films,proto3" json:"films,omitempty"`
}

func (x *GetFilmListResponse) Reset() {
	*x = GetFilmListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_film_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilmListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilmListResponse) ProtoMessage() {}

func (x *GetFilmListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_film_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilmListResponse.ProtoReflect.Descriptor instead.
func (*GetFilmListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_film_proto_rawDescGZIP(), []int{2}
}

func (x *GetFilmListResponse) GetFilms() []*Film {
	if x != nil {
		return x.Films
	}
	return nil
}

type GetFilmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFilmRequest) Reset() {
	*x = GetFilmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_film_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilmRequest) ProtoMessage() {}

func (x *GetFilmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_film_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilmRequest.ProtoReflect.Descriptor instead.
func (*GetFilmRequest) Descriptor() ([]byte, []int) {
	return file_rpc_film_proto_rawDescGZIP(), []int{3}
}

func (x *GetFilmRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateFilmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type   string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	YtLink string `protobuf:"bytes,4,opt,name=yt_link,json=ytLink,proto3" json:"yt_link,omitempty"`
	Active int64  `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *UpdateFilmRequest) Reset() {
	*x = UpdateFilmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_film_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFilmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilmRequest) ProtoMessage() {}

func (x *UpdateFilmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_film_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilmRequest.ProtoReflect.Descriptor instead.
func (*UpdateFilmRequest) Descriptor() ([]byte, []int) {
	return file_rpc_film_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFilmRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFilmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFilmRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateFilmRequest) GetYtLink() string {
	if x != nil {
		return x.YtLink
	}
	return ""
}

func (x *UpdateFilmRequest) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

type DeleteFilmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteFilmRequest) Reset() {
	*x = DeleteFilmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_film_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFilmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilmRequest) ProtoMessage() {}

func (x *DeleteFilmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_film_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilmRequest.ProtoReflect.Descriptor instead.
func (*DeleteFilmRequest) Descriptor() ([]byte, []int) {
	return file_rpc_film_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFilmRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFilmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteFilmResponse) Reset() {
	*x = DeleteFilmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_film_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFilmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilmResponse) ProtoMessage() {}

func (x *DeleteFilmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_film_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilmResponse.ProtoReflect.Descriptor instead.
func (*DeleteFilmResponse) Descriptor() ([]byte, []int) {
	return file_rpc_film_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFilmResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_rpc_film_proto protoreflect.FileDescriptor

var file_rpc_film_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x70, 0x63, 0x5f, 0x66, 0x69, 0x6c, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x0a, 0x66, 0x69, 0x6c, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x6c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x79, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x79, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x14,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x66,
	0x69, 0x6c, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e,
	0x46, 0x69, 0x6c, 0x6d, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x6d, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x46, 0x69, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7c, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x79, 0x74,
	0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x79, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2c, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x1f,
	0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6f, 0x73,
	0x75, 0x63, 0x68, 0x2f, 0x66, 0x63, 0x2d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_film_proto_rawDescOnce sync.Once
	file_rpc_film_proto_rawDescData = file_rpc_film_proto_rawDesc
)

func file_rpc_film_proto_rawDescGZIP() []byte {
	file_rpc_film_proto_rawDescOnce.Do(func() {
		file_rpc_film_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_film_proto_rawDescData)
	})
	return file_rpc_film_proto_rawDescData
}

var file_rpc_film_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_film_proto_goTypes = []interface{}{
	(*CreateFilmRequest)(nil),   // 0: pb.CreateFilmRequest
	(*GetFilmListRequest)(nil),  // 1: pb.GetFilmListRequest
	(*GetFilmListResponse)(nil), // 2: pb.GetFilmListResponse
	(*GetFilmRequest)(nil),      // 3: pb.GetFilmRequest
	(*UpdateFilmRequest)(nil),   // 4: pb.UpdateFilmRequest
	(*DeleteFilmRequest)(nil),   // 5: pb.DeleteFilmRequest
	(*DeleteFilmResponse)(nil),  // 6: pb.DeleteFilmResponse
	(*Film)(nil),                // 7: pb.Film
}
var file_rpc_film_proto_depIdxs = []int32{
	7, // 0: pb.GetFilmListResponse.films:type_name -> pb.Film
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_film_proto_init() }
func file_rpc_film_proto_init() {
	if File_rpc_film_proto != nil {
		return
	}
	file_film_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_film_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFilmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_film_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFilmListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_film_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFilmListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_film_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFilmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_film_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFilmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_film_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFilmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_film_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFilmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_film_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_film_proto_goTypes,
		DependencyIndexes: file_rpc_film_proto_depIdxs,
		MessageInfos:      file_rpc_film_proto_msgTypes,
	}.Build()
	File_rpc_film_proto = out.File
	file_rpc_film_proto_rawDesc = nil
	file_rpc_film_proto_goTypes = nil
	file_rpc_film_proto_depIdxs = nil
}
