// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: service_fc_order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FcOrder_CreateAccount_FullMethodName = "/pb.FcOrder/CreateAccount"
)

// FcOrderClient is the client API for FcOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FcOrderClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
}

type fcOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewFcOrderClient(cc grpc.ClientConnInterface) FcOrderClient {
	return &fcOrderClient{cc}
}

func (c *fcOrderClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, FcOrder_CreateAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FcOrderServer is the server API for FcOrder service.
// All implementations must embed UnimplementedFcOrderServer
// for forward compatibility
type FcOrderServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	mustEmbedUnimplementedFcOrderServer()
}

// UnimplementedFcOrderServer must be embedded to have forward compatible implementations.
type UnimplementedFcOrderServer struct {
}

func (UnimplementedFcOrderServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedFcOrderServer) mustEmbedUnimplementedFcOrderServer() {}

// UnsafeFcOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FcOrderServer will
// result in compilation errors.
type UnsafeFcOrderServer interface {
	mustEmbedUnimplementedFcOrderServer()
}

func RegisterFcOrderServer(s grpc.ServiceRegistrar, srv FcOrderServer) {
	s.RegisterService(&FcOrder_ServiceDesc, srv)
}

func _FcOrder_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FcOrderServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FcOrder_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FcOrderServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FcOrder_ServiceDesc is the grpc.ServiceDesc for FcOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FcOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FcOrder",
	HandlerType: (*FcOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _FcOrder_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_fc_order.proto",
}
